import {
  Armchair,
  Baby,
  BedDouble,
  Car,
  Laptop,
  ShowerHead,
  Utensils,
  WashingMachine,
} from "lucide-react";
import type { RoomCardProps } from "../../../../components/room-card/room-card";

export const roomsMock = [
  {
    id: "sala",
    name: "Sala",
    itemsCount: 18,
    boxesCount: 4,
    icon: Armchair,
    variant: "blue",
  },
  {
    id: "cozinha",
    name: "Cozinha",
    itemsCount: 24,
    boxesCount: 6,
    icon: Utensils,
    variant: "green",
  },
  {
    id: "quarto",
    name: "Quarto",
    itemsCount: 15,
    boxesCount: 3,
    icon: BedDouble,
    variant: "purple",
  },
  {
    id: "banheiro",
    name: "Banheiro",
    itemsCount: 8,
    boxesCount: 2,
    icon: ShowerHead,
    variant: "cyan",
  },
  {
    id: "garagem",
    name: "Garagem",
    itemsCount: 12,
    boxesCount: 3,
    icon: Car,
    variant: "orange",
  },
  {
    id: "escritorio",
    name: "Escritório",
    itemsCount: 10,
    boxesCount: 2,
    icon: Laptop,
    variant: "teal",
  },
  {
    id: "quarto-criancas",
    name: "Quarto das crianças",
    itemsCount: 6,
    boxesCount: 1,
    icon: Baby,
    variant: "pink",
  },
  {
    id: "lavanderia",
    name: "Lavanderia",
    itemsCount: 5,
    boxesCount: 1,
    icon: WashingMachine,
    variant: "purple",
  },
] satisfies (RoomCardProps & { id: string })[];
